name: Build Packages

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pyqt5 python3-pip fpm
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile yourscript.py

      - name: Create .deb package
        run: |
          mkdir -p package/usr/local/bin
          cp dist/yourscript package/usr/local/bin/tonebeat
          fpm -s dir -t deb -n tonebeat -v 1.0 package/=/

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: tonebeat-linux-deb
          path: ./*.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile yourscript.py

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v3
        with:
          name: tonebeat-windows-exe
          path: dist/yourscript.exe
